import Navbar from "@/frontend/components/Navbar/Navbar";
import { UserContextProvider } from "@/frontend/context/UserContext";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Launchpad Assessment",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <UserContextProvider>
                    <AppRouterCacheProvider>
                        <Navbar />
                        {children}
                    </AppRouterCacheProvider>
                </UserContextProvider>
            </body>
        </html>
    );
}
